server:
  port: 8081
  servlet:
    context-path: /test
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/psychological_counseling?useUnicode=true&useSSL=false&characterEncoding=utf8
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    servlet:
      load-on-startup: 1

logging:
  level:
    com:
      lyh: debug

#mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml

  configuration:
    map-underscore-to-camel-case: true
mapper:
  enum-as-simple-type: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



